namespace StronglyTypedId.Sources;

public static class StronglyTypedIdAttribute
{
    public static String Source
    {
        get => """
               // <auto-generated/>
               
               namespace StronglyTypedId.Attributes;
               
               [AttributeUsage(AttributeTargets.Struct)]
               public class StronglyTypedIdAttribute : Attribute
               {
               }
               """;
    }
}